name: telegram release

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Flutter CI"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_FLUTTER }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Release new version https://github.com/${{ github.repository }}/actions, action finished.
